#!/usr/bin/env python3
"""
bootstrap-chisq.py

--> Code in support of the paper "Surprising payouts in parimutuel numbers games"
--> Provided under a GPL v3.0 license
--> This file generated by Claude Fable

Nonparametric bootstrap confidence interval for the chi-square divergence
chi^2(m||q) of the uniform distribution m from a lottery betting distribution q.

  chi^2(m||q) = sum_u (1/t - q_u)^2 / q_u        [the quantity in (3.3)]
  chi^2(q||m) = t * sum_u q_u^2 - 1              [the "collision" direction]

Input: a CSV with one row per number, e.g.

    Number,AmountWagered,Probability
    0,7512.0,0.00432069545251405
    1,1226.0,0.0007051614250242579
    ...

Only the number column and one frequency column are needed; by default the
script uses the amount-wagered column and normalizes it itself (equivalent to
the Probability column, but avoids depending on the file's rounding).

METHOD
------
Each bootstrap replicate resamples the wagering units multinomially from the
observed distribution and recomputes the divergence on the resampled
frequencies.  The unit of resampling is the minimum wager (default $0.50),
so a file totaling $1.74M represents ~3.48M units.

  * Independence.  Units are treated as independent draws from q.  This is
    conservative in one direction and anticonservative in another: a single
    player betting $5 on one number is one decision but ten units, which
    understates uncertainty; conversely, treating a one-week sample as
    representative of a stationary q ignores week-to-week variation, which
    the paper addresses separately via the split-half check.  Use
    --unit to test sensitivity: larger units (e.g. --unit 5) give fewer,
    coarser draws and wider intervals.

  * Plug-in bias.  chi^2(m||q) depends on 1/q_u, so the plug-in estimate is
    upward biased when the smallest cells are noisy.  The bootstrap
    distribution's mean minus the plug-in estimate is the usual bootstrap
    bias estimate; the script reports it.  With cells as well populated as
    these (minimum cell ~1,250 units), the bias should be negligible.

USAGE
-----
    python3 bootstrap-chisq.py CA-wagers-straight.csv
    python3 bootstrap-chisq.py KY-wagers.csv --reps 10000 --seed 20260716
    python3 bootstrap-chisq.py CA-straight-and-combo.csv --unit 5.0
"""

import argparse
import csv
import sys

try:
    import numpy as np
except ImportError:
    sys.exit("This script requires numpy (pip install numpy).")


def load_frequencies(path, number_col, value_col):
    """Return (numbers, weights) from the CSV, in file order."""
    numbers, weights = [], []
    with open(path, newline="") as f:
        reader = csv.DictReader(f)
        if number_col not in reader.fieldnames or value_col not in reader.fieldnames:
            sys.exit(
                f"Columns {number_col!r}/{value_col!r} not found. "
                f"File has: {reader.fieldnames}"
            )
        for row in reader:
            numbers.append(int(row[number_col]))
            weights.append(float(row[value_col]))
    return np.array(numbers), np.array(weights, dtype=float)


def chisq_m_from_q(q):
    """chi^2(m||q) = sum (1/t - q_u)^2 / q_u.  Uniform m in the first slot."""
    t = len(q)
    return float(np.sum((1.0 / t - q) ** 2 / q))


def chisq_q_from_m(q):
    """chi^2(q||m) = t * sum q_u^2 - 1.  The collision direction."""
    t = len(q)
    return float(t * np.sum(q**2) - 1.0)


def main():
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("csv", help="per-number frequency CSV")
    p.add_argument("--number-col", default="Number")
    p.add_argument("--value-col", default="AmountWagered",
                   help="column to normalize into q (default: AmountWagered)")
    p.add_argument("--unit", type=float, default=0.50,
                   help="wagering unit in dollars; sets the resample size "
                        "(default: 0.50). Ignored with --n-units.")
    p.add_argument("--n-units", type=int, default=None,
                   help="resample size, if known directly (e.g. ticket count)")
    p.add_argument("--reps", type=int, default=5000)
    p.add_argument("--seed", type=int, default=20260716)
    p.add_argument("--level", type=float, default=95.0,
                   help="confidence level in percent (default: 95)")
    args = p.parse_args()

    numbers, weights = load_frequencies(args.csv, args.number_col, args.value_col)
    if np.any(weights <= 0):
        sys.exit("Some cells have zero or negative weight; chi^2(m||q) is "
                 "undefined for zero cells. Inspect the data.")

    total = weights.sum()
    q_hat = weights / total
    t = len(q_hat)

    n = args.n_units if args.n_units is not None else int(round(total / args.unit))

    point_mq = chisq_m_from_q(q_hat)
    point_qm = chisq_q_from_m(q_hat)

    rng = np.random.default_rng(args.seed)
    boot_mq = np.empty(args.reps)
    boot_qm = np.empty(args.reps)
    for i in range(args.reps):
        counts = rng.multinomial(n, q_hat)
        if np.any(counts == 0):
            # A zero cell makes chi^2(m||q) infinite. With these sample sizes
            # this should never fire; if it does, the data are too sparse for
            # an unsmoothed plug-in estimate and the run should be reported.
            sys.exit(f"Replicate {i} produced an empty cell; n={n} is too "
                     f"small relative to the smallest q_u ({q_hat.min():.2e}).")
        q_star = counts / n
        boot_mq[i] = chisq_m_from_q(q_star)
        boot_qm[i] = chisq_q_from_m(q_star)

    lo_pct = (100.0 - args.level) / 2.0
    hi_pct = 100.0 - lo_pct

    print(f"file:              {args.csv}")
    print(f"numbers (t):       {t}")
    print(f"total wagered:     ${total:,.2f}")
    print(f"resample size (n): {n:,}"
          + ("" if args.n_units is not None else f"  (= total / ${args.unit:.2f})"))
    print(f"replicates:        {args.reps:,}   seed: {args.seed}")
    print()
    print(f"smallest q_u:      {q_hat.min():.3e} "
          f"(number {int(numbers[q_hat.argmin()]):03d}; "
          f"~{q_hat.min()*n:,.0f} units)")
    print(f"uniform 1/t:       {1.0/t:.3e}")
    print()

    for name, point, boot in (("chi^2(m||q)", point_mq, boot_mq),
                              ("chi^2(q||m)", point_qm, boot_qm)):
        lo, hi = np.percentile(boot, [lo_pct, hi_pct])
        print(f"{name}")
        print(f"  plug-in estimate     {point:.6f}")
        print(f"  bootstrap SE         {boot.std(ddof=1):.6f}")
        print(f"  bootstrap bias est.  {boot.mean() - point:+.6f}")
        print(f"  {args.level:g}% percentile CI   ({lo:.4f}, {hi:.4f})")
        print()

    print("For the manuscript, round to the precision the argument uses, e.g.")
    lo, hi = np.percentile(boot_mq, [lo_pct, hi_pct])
    print(f'  "$\\chi^2(m \\Vert q) \\approx {point_mq:.3f}$ '
          f'(bootstrap 95\\% CI {lo:.3f}--{hi:.3f})"')


if __name__ == "__main__":
    main()
